In [ ]:
import sys
from pathlib import Path

# Add project root to path
project_root = Path().resolve().parent
sys.path.insert(0, str(project_root))

from src.sanitization.simple_sanitizer import clean_all_pandas_df

In [2]:
path = "Data/all_records_raw.xlsx"
import pandas as pd
df = pd.read_excel(path)
df["Name"] = df["Name"].astype(str)

In [3]:
df = clean_all(df=df, save_location="Data/clean_names.csv", rules_loc="/Users/williamryan/PROJECTS/All_Records_Fuzzy_Matching/workspace/files/rules.json")

In [4]:
df

,Internal ID,Name,Created Date,Sectors,Clean_Name
0,333317,nan,2022-09-13 23:13:53.907,"Lead, zinc and tin ores and concentrates",Nan
1,333316,nan,2022-09-13 23:13:53.907,Computer and related services,Nan
2,333315,nan,2022-09-13 23:13:53.907,Aviation Gasoline,Nan
3,333314,nan,2022-09-13 23:13:53.907,"Ash for treatment, Re-processing of ash into c...",Nan
4,333313,nan,2022-09-13 23:13:53.907,Aviation Gasoline,Nan
...,...,...,...,...,...
631824,169379,ZYNGA INC.,2021-08-11 00:00:00.000,"Computer and related services|Recreational, cu...",Zynga
631825,145661,ZYNGA INC.,2022-05-05 00:00:00.000,"Recreational, cultural and sporting services|C...",Zynga
631826,210854,ZYNGA INC.,2022-05-03 00:00:00.000,"Computer and related services|Recreational, cu...",Zynga
631827,269849,ZZZ Meats Pty Ltd,2022-06-26 00:00:00.000,Meat products nec,Zzz Meats
631828,236103,ZZZFL0066 - FLEXTRONICS TECHNOLOGIES India PVT...,2021-08-29 00:00:00.000,"Sale, maintenance, repair of motor vehicles, m...",Zzzflflextronics Technologies India Pvt

In [6]:
#df.to_csv("Data/All_Records_Clean_Names.csv", index=False)